version: "3.7"
services: 
    mongodb:
        container_name: mongodb
        image: mongo:4.2.3
        ports: 
            - "27017:27017"
    mysqldb:
        container_name: mysqldb
        image: mysql:8.0.19  
        ports:
            - "3306:3306"
        environment: 
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
    postgresdb:
        container_name: postgresdb
        image: postgres:9.6.17
        ports: 
            - "5432:5432"
        environment: 
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
             
